#define REGISTRY_OVERLAY_KEY		L"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ShellIconOverlayIdentifiers"
#define REGISTRY_CLSID				L"CLSID"
#define REGISTRY_IN_PROCESS			L"InprocServer32"
#define REGISTRY_THREADING			L"ThreadingModel"
#define REGISTRY_APARTMENT			L"Apartment"
#define REGISTRY_VERSION			L"Version"
#define REGISTRY_VERSION_NUMBER		L"1.0"
