/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liferay_nativity_util_windows_WindowsUtil */

#ifndef _Included_com_liferay_nativity_util_windows_WindowsUtil
#define _Included_com_liferay_nativity_util_windows_WindowsUtil
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _loaded */
/* Inaccessible static: _logger */
/*
 * Class:     com_liferay_nativity_util_windows_WindowsUtil
 * Method:    _setRootFolder
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_liferay_nativity_util_windows_WindowsUtil__1setRootFolder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_liferay_nativity_util_windows_WindowsUtil
 * Method:    _updateExplorer
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_liferay_nativity_util_windows_WindowsUtil__1updateExplorer
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_liferay_nativity_util_windows_WindowsUtil
 * Method:    _updateRenameExplorer
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_liferay_nativity_util_windows_WindowsUtil__1updateRenameExplorer
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
