/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liferay_nativity_control_win_WindowsNativityUtil */

#ifndef _Included_com_liferay_nativity_control_win_WindowsNativityUtil
#define _Included_com_liferay_nativity_control_win_WindowsNativityUtil
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _load */
/* Inaccessible static: _loaded */
/* Inaccessible static: _logger */
/*
 * Class:     com_liferay_nativity_control_win_WindowsNativityUtil
 * Method:    setSystemFolder
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_liferay_nativity_control_win_WindowsNativityUtil_setSystemFolder
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_liferay_nativity_control_win_WindowsNativityUtil
 * Method:    updateExplorer
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_liferay_nativity_control_win_WindowsNativityUtil_updateExplorer
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
